---
# tasks file for roles/api
- name: Run API
  docker_container:
    name: API
    image: guillaume225/simple-api-student:1.0
    state: started
    networks:
      - name: app-network
    ports:
      - "8080:8080"
    env:
      DB_host: my-postgres-container
      DB_port: "5432"
      DB_name: db
      DB_user: usr
      DB_mdp: pwd
      BACKEND_PORT: "8080"

  vars: 
     ansible_python_interpreter: /usr/bin/python3