---
# tasks file for roles/database
- name: Run database
  docker_container:
    name: my-postgres-container
    image: guillaume225/my-postgres-db:1.0
    state: started
    networks:
      - name: app-network
    env:
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
      POSTGRES_USER: usr 
  vars: 
    ansible_python_interpreter: /usr/bin/python3