# Première étape : Compilation
FROM eclipse-temurin:17-jdk-alpine AS build

# Définir le répertoire de travail
WORKDIR /usr/src/myapp

# Copier le fichier source Java dans le conteneur
COPY Main.java .

# Compiler le fichier Java
RUN javac Main.java

# Deuxième étape : Exécution
FROM eclipse-temurin:17-jre-alpine

# Copier le fichier compilé de l'étape précédente
COPY --from=build /usr/src/myapp/Main.class .

# Commande pour exécuter le programme Java
CMD ["java", "Main"]
